### PR TITLE
Tab logic cleanup

### PR DESCRIPTION
**Pull request by BenMusch**
This PR cleans up the tab logic library into 1 main library with some sub-modules. Goals are to separate:

- stats calculations
- rankings
- pairing

And also to improve performance

### CODE REVIEW

**Comment by BenMusch** [comment]
Some performance stats:

Loading speaker rankings went from ~16s to ~6s

Loading debater rankings went from ~17s to ~7s

Curious @ifly6: Is that about comparable to what you observed?

**Comment by ifly6** [comment]
I was able to halve runtime by introducing struts. There's a number of Django query optimisations I also introduced in my pull request.

**Comment by BenMusch** [comment]
@ifly6 	Thanks for the info! Do you mind if I continue to extract your work on that branch to this one (making sure to keep you as the author on git)?

**Comment by ifly6** [comment]
Do it!

**Comment by BenMusch** [comment]
TODO to self: Fix merge conflict, it's important

**Pull request merged**
