### PR TITLE
Add note in docs that team codes aren't a released feature yet

### PR DESCRIPTION
**Pull request by BenMusch**
cc @roddajohn, feel free to remove this once everything is done

### CODE REVIEW

**Comment by roddajohn** [comment]
#247 is merged right ?

**Comment by BenMusch** [comment]
@roddajohn Oh I'm stupid -- I totally missed the html changes at the bottom. I think there's still some more (small) changes to make. Specifically: Team codes should also be added to the public teams lists _and_ to the team drop-down in the ballots form, so that basically no publicly-visible page has any normal team name on it

**Comment by roddajohn** [comment]
Got it — I'll make those changes soon!

**Comment by roddajohn** [comment]
I'm working on it and came across this interesting question — on the public teams page, what do we think about redacting school names (and maybe debater names) if team codes are in use?  I'm thinking right now to add two flags to allow the user to control that.

**Comment by BenMusch** [comment]
@roddajohn IMO, we can show the normal team names and schools there. What matters is for submitting ballots and viewing pairings, where it affects the judge

**Comment by BenMusch** [comment]
Actually, changed my mind. Hide the schools on that page so judges can't look it up if they get curious

**Comment by roddajohn** [comment]
Ha!  We had the same thoughts, I have a toggle that the tournament can set

**Comment by roddajohn** [comment]
See #257 which I think solves this

**Comment by BenMusch** [comment]
Will review this weekend!

**Pull request merged**
